MovieApp.UI/Controllers/TheatreController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using MovieApp.Entity;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;

namespace MovieApp.UI.Controllers
{
    public class TheatreController : Controller
    {
        private IConfiguration _configuration;
        public TheatreController(IConfiguration configuration)
        {
            _configuration = configuration;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult AddTheatre()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddTheatre(TheatreModel theatreModel)
        {
            ViewBag.status = "";
            using (HttpClient client = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(theatreModel), Encoding.UTF8, "application/json");
                string endPoint = _configuration["WebApiURL"] + "Theatre/AddTheatre";
                using (var response = await client.PostAsync(endPoint, content))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        ViewBag.status = "Ok";
                        ViewBag.message = "Register successfully!";
                    }
                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "Wrong entries!";
                    }
                }
            }
            return View();
        }


        [HttpGet]
        public async Task<IActionResult> ShowTheatreDetails()
        {
            //Fetch API,Axios Api, HTTPClient
            //HTTP Req/response

            ViewBag.status = "";
            using (HttpClient client = new HttpClient())
            {

                string endPoint = _configuration["WebApiURL"] + "Theatre/SelectTheatre";
                using (var response = await client.GetAsync(endPoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await response.Content.ReadAsStringAsync();
                        var theatreModels = JsonConvert.DeserializeObject<IEnumerable<TheatreModel>>(result);

                        return View(theatreModels);
                    }

                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "Wrong user entries!";
                    }
                }
            }
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> DeleteTheatreById(int theatreId)
        {
            using (HttpClient client = new HttpClient())
            {
                string endpoint = _configuration["WebApiURL"] + "Theatre/FindTheatreById?TheatreId=" + theatreId;
                using (var response = await client.GetAsync(endpoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await response.Content.ReadAsStringAsync();
                        // var userModels = Newtonsoft.Json.JsonSerializer.Deserialize<List<UserModel>>(result);
                        var theatreModel = JsonConvert.DeserializeObject<TheatreModel>(result);
                        return View(theatreModel);
                    }
                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "Wrong entries";
                    }
                }

                return View();
            }
        }

        [HttpPost]
        public async Task<IActionResult> DeleteTheatreById(TheatreModel theatreModel)
        {
            using (HttpClient client = new HttpClient())
            {

                string endpoint = _configuration["WebApiURL"] + "Theatre/DeleteTheatre?theatreId=" + theatreModel.TheatreId;
                using (var response = await client.DeleteAsync(endpoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        ViewBag.status = "Success";
                        ViewBag.message = "Movie-Deleted-Successfuly";
                    }
                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "Invalid input ";
                    }
                }
            }
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> EditTheatreById(int theatreId)
        {
            string URL = _configuration["WebApiURL"] + "Theatre/FindTheatreById?TheatreId=" + theatreId;
            using (HttpClient client = new HttpClient())
            {
                using (var response = await client.GetAsync(URL))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await response.Content.ReadAsStringAsync();
                        //var theatreModel = JsonConvert.DeserializeObject<TheatreModel>(result); // getting only single record of usermodel

                        //return View(theatreModel);
                        return View(JsonConvert.DeserializeObject<TheatreModel>(result));
                    }
                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "Wrong theatre entries!";
                    }
                }
            }
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> EditTheatreById(TheatreModel theatreModel)
        {
            StringContent body = new StringContent(JsonConvert.SerializeObject(theatreModel), Encoding.UTF8, "application/json");
            string endpoint = _configuration["WebApiBaseUrl"] + "Theatre/UpdateTheatre";
            using (HttpClient client = new HttpClient())
            {
                using (var response = await client.PutAsync(endpoint, body))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        ViewBag.status = "Success";
                        ViewBag.message = "Theatre Updated Successfully..!!";
                    }
                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "Sorry.. Unable To Update..!!";
                    }
                }
            }
            return View();
        }
    }
}

MovieApp.UI/Views/Theatre/AddTheatre.cshtml
@model MovieApp.Entity.TheatreModel
@{
    ViewData["Title"] = "AddTheatre";
}

<h1>Add Theatre</h1>

<form method="post">
    <div class="form-group">
        <label for="Firstname">Theatre Name</label>
        <input type="text" class="form-control" asp-for="TheatreName">
    </div>
    <div class="form-group">
        <label for="Firstname">Theatre Location</label>
        <input type="text" class="form-control" asp-for="TheatreLocation">
    </div>
    <div class="form-group">
        <label for="Firstname">Theatre Capacity</label>
        <input type="text" class="form-control" asp-for="TheatreCapacity">
    </div>
    <input type="submit" class="btn btn-primary" value="Add Theatre">
    <button type="button" class="btn btn-secondary">Reset</button>
    <hr />
    @if (ViewBag.status == "Ok")
    {
        <div class="alert alert-success">
            @ViewBag.message
        </div>
    }
    else if (ViewBag.status == "Error")
    {
        <div class="alert alert-danger">
            @ViewBag.message
        </div>
    }
    <hr />
</form>

MovieApp.UI/Views/Theatre/DeleteTheatreById.cshtml
@model MovieApp.Entity.TheatreModel
@{
    ViewData["Title"] = "DeleteTheatreById";
}

<h1>Delete Theatre </h1>

<div class="container">
<form method="post">
     <div class="form-group">
        <label for="Firstname">TheatreId</label>
        <input type="text" class="form-control" asp-for="TheatreId" disabled="disabled" >
    </div>
    <div class="form-group">
        <label for="Firstname">TheatreName</label>
        <input type="text" class="form-control" asp-for="TheatreName" disabled="disabled">
    </div>
    <div class="form-group">
        <label for="Firstname">TheatreLocation</label>
        <input type="text" class="form-control" asp-for="TheatreLocation" disabled="disabled">
    </div>
    <div class="form-group">
        <label for="Firstname">TheatreCapacity</label>
        <input type="text" class="form-control" asp-for="TheatreCapacity" disabled="disabled">
    </div>
    <input type="submit" class="btn btn-primary" value="Confirm-Delete">
  
    <hr />
    @if (ViewBag.status == "Success")
    {
        <div class="alert alert-success">
            @ViewBag.message
        </div>
    }
    else if (ViewBag.status == "Error")
    {
        <div class="alert alert-danger">
            @ViewBag.message
        </div>
    }
    <hr />
 
</form>
   </div>

MovieApp.UI/Views/Theatre/EditTheatreById.cshtml
@model MovieApp.Entity.TheatreModel
@{
    ViewData["Title"] = "EditTheatreById";
}

<h1>Edit Theatre</h1>

<a asp-action="ShowTheatreDetails">Show Theatres</a>
<form method="post">
    <div class="form-group">
        <label class="form-label">Theatre Name</label>
        <input type="text" class="form-control" asp-for="TheatreName">
    </div>
    <div class="form-group">
        <label class="form-label">Theatre Location</label>
        <input type="text" class="form-control" asp-for="TheatreLocation">
    </div>
    <div class="form-group">
        <label class="form-label">Theatre Capacity</label>
        <input type="email" class="form-control" asp-for="TheatreCapacity">
    </div>
    <button type="submit" class="btn btn-primary" value="Update">Update Theatre</button>"
    <button type="reset"  class="btn btn-secondary">Clear Form</button>
    <hr />

    @if (ViewBag.status == "Success")
    {
        <div class="alert alert-success">
            @ViewBag.message
        </div>
    }
    else
    {
        <div class="alert alert-danger">
            @ViewBag.message
        </div>
    }
</form>

MovieApp.UI/Views/Theatre/ShowTheatreDetails.cshtml
@model IEnumerable<MovieApp.Entity.TheatreModel>
@{
    ViewData["Title"] = "ShowTheatreDetails";
}

<h1>Show Theatre Details</h1>

<hr />

    <table class="table table-bordered bg-primary">
       <thead>
         <tr>
           <th>TheatreId</th>
           <th>TheatreName</th>
           <th>TheatreLocation</th>
           <th>TheatreCapacity</th>
           <th>Edit</th>
           <th>Delete</th>
          </tr>
      </thead>
         
    <tbody>
         @foreach(var item in Model)
         {
         <tr>
         <td>@item.TheatreId</td>
          <td>@item.TheatreName</td>
           <td>@item.TheatreLocation</td>
           <td>@item.TheatreCapacity</td>
            <td><a asp-action="EditTheatreById" asp-controller="Theatre" asp-route-TheatreId=@item.TheatreId>Edit</a></td>
            <td><a asp-action="DeleteTheatreById" asp-controller="Theatre" asp-route-TheatreId=@item.TheatreId>Delete</a></td>
         </tr>
         }
    </tbody>
   </table>